studioml/studio

README
README.md
docs/artifacts.md
docs/cloud.md
docs/ec2_setup.md
docs/hyperparams.md
docs/remote_worker.md
docs/setup_database.md
setup.py
studio/auth.py
studio/ec2cloud_worker.py
studio/fs_tracker.py
studio/model.py
studio/scripts/ec2_worker_startup.sh
studio/scripts/gcloud_worker_startup.sh
studio/scripts/studio-add-credentials
studio/scripts/studio-start-remote-worker
studio/tests/fs_tracker_test.py

This will require us to talk with users when the git pull the latest version to rename their .tfstudio directories to .studioml

change naming from tfstudio to studioml, including the options directory

---

setup.py
studio/firebase_artifact_store.py
studio/gcloud_artifact_store.py
studio/model.py
studio/s3_artifact_store.py

I have included changes here for adding the bucket values to the artifacts individually to allow data to come from multiple places.
Interested in feedback.
Thanks

Enable explicit bucket data per artifact to allow diversity

---

studio/deploy_app.sh
studio/firebase_artifact_store.py
studio/runner.py
studio/scripts/ec2_worker_startup.sh
studio/scripts/gcloud_worker_startup.sh
studio/tests/local_worker_test.py
studio/tests/runner_test.py

okay, so all tests pass (at least for me) in this PR. 
I urge everyone to run tests (even if you don't have aws / gcloud credentials, respective tests will be simply skipped) *before* merging PR's (even if you have an approval) - this will save us from awkward situations when there are syntax errors in master branch.

All tests green 

---

studio/runner.py

Saw some spelling errors as I was looking through the code.

runner.py spelling errors

---

examples/pytorch/mnist.py
studio/__init__.py
studio/torch/__init__.py
studio/torch/saver.py
studio/torch/summary.py
studio/torch/summary_test.py

Closing #155 
Added:
- Saver class, mimicking Tensorflow interface
- Events file writer, compatible with TB

Torch tools to make using Studio easy

---

studio/auth.py
studio/model.py
studio/runner.py
studio/util.py

This uses multiprocessing to parallelize the addition of experiments to the database which has been a major time bottleneck for submitting experiments. On my 6700k cpu, the time it takes to submit 100 experiments went down from 200+ seconds to around 20.

Parallel adding of experiments to db during submission

---

.travis.yml
README.rst
docs/README.rst
docs/conf.py
examples/keras/train_mnist_keras.py
examples/pytorch/mnist.py
requirements.txt
studio/ec2cloud_worker.py
studio/model.py
studio/tests/check_style.sh
studio/tests/http_provider_test.py
studio/tests/model_util_test.py
studio/tests/test_config_http_server.yaml
studio/torch/__init__.py
studio/torch/saver.py
studio/torch/summary.py
studio/torch/summary_test.py
test_requirements.txt

Runs the tests that don't require credentials (does not run cloud workers / remote workers / distributed queue tests), does not run checkstyle (flake8)

108 travis tests

---

studio/auth.py
studio/cloud_worker_util.py
studio/firebase_artifact_store.py
studio/fs_tracker.py
studio/gcloud_worker.py
studio/hyperparameter.py
studio/optimizer_plugins/cmaes.py
studio/optimizer_plugins/opt_util.py
studio/pubsub_queue.py
studio/pyrebase.py
studio/runner.py
studio/tests/git_util_test.py
studio/tests/hyperparam_test.py
studio/tests/save_model.py
studio/tests/test_array.py
studio/util.py

This is fix for issue #161. It adds two things: A cooldown on how often the api key file can be written and also a loop to retry loading the api key json if it fails.

Json Bug Fix

---

docs/artifacts.rst
studio/auth.py
studio/model.py
studio/optimizer_plugins/cmaes.py
studio/optimizer_plugins/opt_util.py
studio/runner.py
studio/scripts/ec2_worker_startup.sh
studio/tartifact_store.py
studio/util.py

This pull request fixes some bugs with loading the api key json and submitting experiments.
It also adds an ignore file which allows you to ignore certain files in the workspace directory.

Studioml ignore file + bug fixes

---

requirements.txt

added google-gax <= 0.15.14 to requirements 

---

studio/experiment.py
studio/http_provider.py
studio/local_worker.py
studio/model.py
studio/remote_worker.py
studio/runner.py

`studio run <experiment_key>` will re-run experiment

rerun functionality

---

studio/fs_tracker.py
studio/tests/test_array.py

By convention, if artifact mapping is not specified, artifact x is mapped to ../x

Artifact mappings 

---

studio/ec2cloud_worker.py
studio/gcloud_worker.py
studio/scripts/ec2_worker_startup.sh
studio/scripts/gcloud_worker_startup.sh
studio/scripts/install_studio.sh

reuse the piece that is responsible for installing python2/3, system packages and cuda on gcloud and ec2 workers

reuse common piece of cloud startup scripts

---

requirements.txt
studio/completion_service/completion_service.py
studio/qclient_cache.py
studio/rabbit.py
studio/rabbit_queue.py
studio/remote_worker.py
studio/runner.py
studio/s3_artifact_store.py
studio/tartifact_store.py

groom pika connections, studioml does not implement full lifecycle management for Queues
ensure RMQ routes are per queue and dont by default mirror messages across multiple queues
S3 and tar failure logging improved

331 config passing bug

---

requirements.txt
studio/rabbit_queue.py

Fixes issue #395 
Changes in pika API usage to comply with version 1.1.0

Switch to pika package version 1.1.0

---

requirements.txt

Fixes #393
Update pip version to 20.0.2

Update requirements for pip.

---

studio/apiserver.py
studio/ec2cloud_worker.py
studio/model.py

Fixes #390 
Updated calls to pyYAML.load() to explicitly specify the loader used.

 Update calls to pyYAML.load().

---

requirements.txt

Fixes #392 
Added tensorflow 1.15.2 dependency to studioml requirements.

Add correct tensorflow dependency.

---

studio/local_queue.py
studio/pubsub_queue.py
studio/sqs_queue.py

Added shutdown() API call to all Queue classes.

---

studio/local_queue.py
studio/local_worker.py
studio/util.py

Fixes #409 
Several improvements are made for local tasks queue handling.
We now control log reprinter thread lifetime so it never exceeds
lifetime of worker process.
Worker process now also monitors the status of tasks queue
to shutdown as soon as queue is inactive - this will help to better manage
worker process on Completion service shutdown.

Improve worker process handling in studio local mode.

---

studio/local_queue.py
studio/local_worker.py
studio/rabbit_queue.py

Removed internal timeout for LocalQueue.
Fixed internal checks in RMQ module for closing channel/connection.

Fixes for LocalQueue and RMQ.

---

studio/rabbit_queue.py

Retries for RMQ queue delete operation.

---

studio/completion_service/completion_service.py
studio/qclient_cache.py
studio/rabbit_queue.py
studio/runner.py

Fixes #422 
Several fixes in RMQ handling logic.

Fixes for handling RMQ workloads queues.

---

studio/keyvalue_provider.py
studio/tartifact_store.py

Fixes #425
Adjusted logger messages levels
to manage logger output volume.

Fixes for logger messages levels.

---

requirements.txt

and remove version locks where possible.
Fixes: #428 
Tested by running simple experiment against datacenter
and small encrypted payload against local k8s cluster.

Clean-up StudioML dependencies

---

studio/apiserver.py
studio/completion_service/completion_service.py
studio/experiment.py
studio/experiment_submitter.py
studio/local_worker.py
studio/model.py
studio/pubsub_queue.py
studio/remote_worker.py
studio/runner.py
studio/sqs_queue.py
studio/util.py

Refactor code to prepare to split out different Completion Service implementation.

---

studio/experiment_submitter.py
studio/model.py
studio/model_setup.py
studio/runner.py
studio/util.py

And some code cleanup.
Fixes #434

Fixes for model_setup logic.

---

requirements.txt

Remove tensorflow dependency.

---

studio/keyvalue_provider.py
studio/local_artifact_store.py
studio/local_db_provider.py
studio/s3_artifact_store.py
studio/s3_provider.py
studio/tartifact_store.py
studio/util.py
tests/artifact_store_test.py
tests/hyperparam_test.py
tests/model_test.py
tests/runner_test.py

Improve logging/error handling in studio artifacts processing. 

---

studio/experiment_submitter.py

Implements #443
Rather trivial extension.

Allow experiment submitter to use external payload builder.

---

studio/dependencies_policy.py
studio/experiment.py
studio/experiment_submitter.py
studio/studio_dependencies_policy.py

Separate dependencies management logic into policy interface.

---

studio/s3_provider.py
studio/s3_storage_handler.py

S3 protocol support for GCP interoperability

GCS S3 compatibility

---

studio/artifact.py
studio/firebase_provider.py
studio/firebase_storage_handler.py
studio/http_storage_handler.py
studio/keyvalue_provider.py
studio/local_db_provider.py
studio/local_storage_handler.py
studio/s3_provider.py
studio/s3_storage_handler.py
studio/storage_handler.py
studio/util.py

Additional implementation fixes
for #391

StudioML experiment cleanup for local execution mode.

---

studio/http_provider.py

Fixes for HTTP artifacts database provider.

---

studio/storage_util.py

Fixes #455 
No more running bash sub-processes for "tar" app.

Switch to using Python tarfile library for tar/untar artifacts operations.

---

studio/keyvalue_provider.py
studio/s3_storage_handler.py
studio/storage_handler.py
studio/tartifact_store.py

For QA purposes, implement the whole experiment bucket cleanup and deletion
if requested by "cleanup_bucket" studioml configuration parameter.

Experiment bucket clean-up.

---

requirements.txt
studio/artifact.py
studio/credentials.py
studio/pubsub_queue.py

Use artifacts credentials to select correct storage provider (S3 vs http)
Dependencies cleanup - remove outdated google-gax package.

Fix for artifacts credentials.

---

requirements.txt
studio/ed25519_key_util.py
studio/encrypted_payload_builder.py
studio/local_worker.py
studio/util.py

Remove packages under GNU software license.

---

studio/__init__.py
studio/artifact.py
studio/auth.py
studio/encrypted_payload_builder.py
studio/experiment.py
studio/fs_tracker.py
studio/http_provider.py
studio/keyvalue_provider.py
studio/local_queue.py
studio/local_worker.py
studio/pubsub_queue.py
studio/pyrebase.py
studio/qclient_cache.py
studio/runner.py
studio/s3_storage_handler.py
studio/storage_handler.py
studio/util.py

Ensure that KeyboardInterrupt is not handled completely in StudioML code.

---

requirements.txt
studio/credentials.py
studio/encrypted_payload_builder.py
studio/experiment_submitter.py
studio/local_worker.py
studio/model.py
studio/qclient_cache.py
studio/rabbit_queue.py
studio/s3_storage_handler.py
studio/sqs_queue.py

Fixes to make SQS work in latest codebase,
extend artifacts/SQS credentials format,
some small fixes.

Fix SQS queues.

---

studio/runner.py

And setup storage credentials for local artifacts,
defined in studio runner app.

Fixes to put workspace back to default artifacts list.

---

studio/local_worker.py
studio/queues/local_queue.py
studio/queues/queues_setup.py
tests/local_worker_test.py
tests/queue_test.py

Make local task queues usable by external evaluation setup.

---

studio/experiments/experiment.py

Process all mutable artifacts for experiment, not only default ones.
